-- Sử dụng cơ sở dữ liệu master
USE master;

-- Xóa cơ sở dữ liệu nếu đã tồn tại
IF EXISTS (SELECT * FROM sys.databases WHERE name = 'Nhom2')
BEGIN
    DROP DATABASE Nhom2;
END;

-- Tạo cơ sở dữ liệu mới
CREATE DATABASE [Nhom2];
GO

-- Sử dụng cơ sở dữ liệu vừa tạo
USE [Nhom2];
GO

-- Tạo bảng KHACHHANG
CREATE TABLE KHACHHANG
(
    MAKHACHHANG CHAR(9) PRIMARY KEY,
    TENCONGTY NVARCHAR(50),
    TENGIAODICH NVARCHAR(50),
    EMAIL VARCHAR(50) UNIQUE,
    DIENTHOAI VARCHAR(11) UNIQUE,
    FAX VARCHAR(20)
);

-- Tạo bảng QuocGia
CREATE TABLE QuocGia
(
    maQG CHAR(10) PRIMARY KEY,
    tenQG NVARCHAR(100)
);

-- Tạo bảng TinhTP
CREATE TABLE TinhTP
(
    maTP CHAR(10) PRIMARY KEY,
    tenTP NVARCHAR(100),
    maQG CHAR(10),
    CONSTRAINT fk_TinhTP_QuocGia FOREIGN KEY (maQG) REFERENCES QuocGia(maQG)
);

-- Tạo bảng QuanHuyen
CREATE TABLE QuanHuyen
(
    maQH CHAR(10) PRIMARY KEY,
    tenQH NVARCHAR(100),
    maTP CHAR(10),
    CONSTRAINT fk_QuanHuyen_TinhTP FOREIGN KEY (maTP) REFERENCES TinhTP(maTP)
);

-- Tạo bảng PhuongXa
CREATE TABLE PhuongXa
(
    maPX CHAR(10) PRIMARY KEY,
    tenPX NVARCHAR(100),
    maQH CHAR(10),
    CONSTRAINT fk_PhuongXa_QuanHuyen FOREIGN KEY (maQH) REFERENCES QuanHuyen(maQH)
);

-- Thêm cột maPX và soNhaTenDuong vào bảng KHACHHANG
ALTER TABLE KHACHHANG
    ADD maPX CHAR(10),
        soNhaTenDuong NVARCHAR(50);

-- Thêm ràng buộc khóa ngoại cho maPX trong bảng KHACHHANG
ALTER TABLE KHACHHANG
    ADD CONSTRAINT fk_KhachHang_PhuongXa FOREIGN KEY (maPX) REFERENCES PhuongXa(maPX);

-- Tạo bảng NHANVIEN
CREATE TABLE NHANVIEN
(
    MANHANVIEN CHAR(9) PRIMARY KEY,
    HO NVARCHAR(10),
    TEN NVARCHAR(30),
    NGAYSINH DATE,
    NGAYLAMVIEC DATE,
    DIACHI NVARCHAR(50),
    SDT VARCHAR(11) UNIQUE,
    LUONGCOBAN MONEY,
    PHUCAP MONEY,
    CONSTRAINT CK_NHANVIEN_NGAYSINH CHECK (DATEDIFF(YEAR, NGAYSINH, GETDATE()) BETWEEN 18 AND 60)
);

-- Tạo bảng DONDATHANG
CREATE TABLE DONDATHANG
(
    SOHOADON CHAR(9) PRIMARY KEY,
    MAKHACHHANG CHAR(9),
    MANHANVIEN CHAR(9),
    NGAYDATHANG DATE,
    NGAYGIAOHANG DATE,
    NGAYCHUYENHANG DATE,
    NOIGIAOHANG NVARCHAR(50),
    CONSTRAINT fk_DONDATHANG_KHACHHANG FOREIGN KEY (MAKHACHHANG) REFERENCES KHACHHANG(MAKHACHHANG),
    CONSTRAINT fk_DONDATHANG_NHANVIEN FOREIGN KEY (MANHANVIEN) REFERENCES NHANVIEN(MANHANVIEN),
    CONSTRAINT chk_DONDATHANG_NGAYGIAOHANG CHECK (NGAYGIAOHANG >= NGAYDATHANG),
    CONSTRAINT chk_DONDATHANG_NGAYCHUYENHANG CHECK (NGAYCHUYENHANG >= NGAYDATHANG)
);

-- Tạo bảng NHACUNGCAP
CREATE TABLE NHACUNGCAP
(
    MACONGTY CHAR(10) PRIMARY KEY,
    TENCONGTY NVARCHAR(50),
    DIACHI NVARCHAR(50),
    DIENTHOAI VARCHAR(11) UNIQUE,
    FAX VARCHAR(20),
    EMAIL NVARCHAR(50) UNIQUE
);

-- Tạo bảng LOAIHANG
CREATE TABLE LOAIHANG
(
    MALOAIHANG CHAR(5) PRIMARY KEY,
    TENLOAIHANG NVARCHAR(50)
);

-- Tạo bảng MATHANG
CREATE TABLE MATHANG
(
    MAHANG CHAR(5) PRIMARY KEY,
    TENHANG NVARCHAR(50),
    MACONGTY CHAR(10),
    MALOAIHANG CHAR(5),
    SOLUONG INT CHECK (SOLUONG >= 0),
    DONVITINH NVARCHAR(5),
    GIAHANG MONEY CHECK (GIAHANG >= 0),
    CONSTRAINT fk_MATHANG_NHACUNGCAP FOREIGN KEY (MACONGTY) REFERENCES NHACUNGCAP(MACONGTY),
    CONSTRAINT fk_MATHANG_LOAIHANG FOREIGN KEY (MALOAIHANG) REFERENCES LOAIHANG(MALOAIHANG)
);

-- Tạo bảng CHITIETDATHANG
CREATE TABLE CHITIETDATHANG
(
    SOHOADON CHAR(9),
    MAHANG CHAR(5),
    GIABAN MONEY CHECK (GIABAN >= 0),
    SOLUONG INT DEFAULT 1 CHECK (SOLUONG > 0),
    MUCGIAMGIA MONEY DEFAULT 0,
    PRIMARY KEY (SOHOADON, MAHANG),
    CONSTRAINT fk_CHITIETDATHANG_DONDATHANG FOREIGN KEY (SOHOADON) REFERENCES DONDATHANG(SOHOADON),
    CONSTRAINT fk_CHITIETDATHANG_MATHANG FOREIGN KEY (MAHANG) REFERENCES MATHANG(MAHANG)
);

-- Xóa ràng buộc mặc định hiện có cho cột SOLUONG trong bảng CHITIETDATHANG (nếu có)
IF EXISTS (SELECT * FROM sys.default_constraints WHERE parent_object_id = OBJECT_ID('CHITIETDATHANG') AND name = 'DF_CHITIETDONHANG_SOLUONG')
BEGIN
    ALTER TABLE CHITIETDATHANG
    DROP CONSTRAINT DF_CHITIETDONHANG_SOLUONG;
END;

-- Thêm ràng buộc mặc định cho cột SOLUONG trong bảng CHITIETDATHANG
ALTER TABLE CHITIETDATHANG
    ADD CONSTRAINT DF_CHITIETDONHANG_SOLUONG DEFAULT 1 FOR SOLUONG;

-- Xóa ràng buộc mặc định hiện có cho cột MUCGIAMGIA trong bảng CHITIETDATHANG (nếu có)
IF EXISTS (SELECT * FROM sys.default_constraints WHERE parent_object_id = OBJECT_ID('CHITIETDATHANG') AND name = 'DF_CHITIETDONHANG_MUCGIAMGIA')
BEGIN
    ALTER TABLE CHITIETDATHANG
    DROP CONSTRAINT DF_CHITIETDONHANG_MUCGIAMGIA;
END;

-- Thêm ràng buộc mặc định cho cột MUCGIAMGIA trong bảng CHITIETDATHANG
ALTER TABLE CHITIETDATHANG
    ADD CONSTRAINT DF_CHITIETDONHANG_MUCGIAMGIA DEFAULT 0 FOR MUCGIAMGIA;
